export enum ReducerActionList {
    SET_TOKEN = 'SET_TOKEN',
    SET_CITY = 'SET_CITY',
    SET_CITY_INDEX = 'SET_CITY_INDEX',
    SET_CITY_LIST = 'SET_CITY_LIST',
    TRIGGER_SEARCH = 'TRIGGER_SEARCH',
    SET_WEATHER = 'SET_WEATHER',
    SET_ERROR = 'SET_WEATHER',
  }